services:
  music-bot:
    image: node:18.20.2-alpine3.19
    container_name: music-bot
    restart: unless-stopped
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    command: sh -c "apk add --no-cache ffmpeg yarn python3 make g++ gcc autoconf automake libtool opus opus-dev git unzip ca-certificates build-base openssh nano py3-pip && yarn install && node main.js"