services:
  music-bot:
    image: node:18.20.2
    container_name: music-bot
    restart: unless-stopped
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    command: sh -c "yarn install && node main.js"